((sh-mode .  ((indent-tabs-mode . nil)
              (sh-indentation   . 2)
              (sh-basic-offset  . 2)))
 (powershell-mode . ((indent-tabs-mode . nil)
                     (powershell-indent . 2))))
