set(MRN_DOC_SOURCES
    _static/favicon.ico
    _static/mroonga.png
    _static/switcher.json
    characteristic.rst
    community.rst
    conf.py
    contribution.rst
    contribution/documentation.md
    contribution/report.rst
    developer.rst
    developer/coding_style.rst
    developer/debug.md
    developer/release.rst
    faq.rst
    faq/mmap_cannot_allocate_memory.rst
    images/mroonga.png
    images/mroonga.svg
    images/storage-mode.png
    images/storage-mode.svg
    images/wrapper-mode.png
    images/wrapper-mode.svg
    index.rst
    install.rst
    install/32bit-note.inc
    install/almalinux.rst
    install/centos.md
    install/debian.rst
    install/docker.rst
    install/fedora.rst
    install/macos.rst
    install/oracle-linux.rst
    install/others.md
    install/ubuntu.rst
    install/windows.rst
    news.rst
    news/0.rst
    news/1.rst
    news/10.rst
    news/11.rst
    news/12.rst
    news/13.md
    news/14.md
    news/2.rst
    news/3.rst
    news/4.rst
    news/5.rst
    news/6.rst
    news/7.rst
    news/8.rst
    news/9.rst
    reference.rst
    reference/full_text_search.rst
    reference/full_text_search/boolean_mode.rst
    reference/full_text_search/scoring.rst
    reference/limitations.rst
    reference/optimizations.rst
    reference/server_variables.rst
    reference/sql_commands.rst
    reference/status_variables.rst
    reference/udf.rst
    reference/udf/mroonga_command.rst
    reference/udf/mroonga_escape.rst
    reference/udf/mroonga_highlight_html.rst
    reference/udf/mroonga_last_insert_grn_id.rst
    reference/udf/mroonga_normalize.rst
    reference/udf/mroonga_snippet.rst
    reference/udf/mroonga_snippet_html.rst
    tutorial.rst
    tutorial/installation_check.rst
    tutorial/mode.rst
    tutorial/storage.rst
    tutorial/tokenizer-list.inc
    tutorial/wrapper.rst
    upgrade.rst)

set(MRN_DOC_HTML_FILES
    _images/storage-mode.png
    _images/wrapper-mode.png
    _static/basic.css
    _static/doctools.js
    _static/documentation_options.js
    _static/favicon.ico
    _static/file.png
    _static/language_data.js
    _static/minus.png
    _static/mroonga.png
    _static/plus.png
    _static/pygments.css
    _static/scripts/bootstrap.js
    _static/scripts/bootstrap.js.LICENSE.txt
    _static/scripts/bootstrap.js.map
    _static/scripts/fontawesome.js
    _static/scripts/fontawesome.js.LICENSE.txt
    _static/scripts/fontawesome.js.map
    _static/scripts/pydata-sphinx-theme.js
    _static/scripts/pydata-sphinx-theme.js.map
    _static/searchtools.js
    _static/sphinx_highlight.js
    _static/styles/pydata-sphinx-theme.css
    _static/styles/pydata-sphinx-theme.css.map
    _static/styles/theme.css
    _static/switcher.json
    _static/vendor/fontawesome/webfonts/fa-brands-400.ttf
    _static/vendor/fontawesome/webfonts/fa-brands-400.woff2
    _static/vendor/fontawesome/webfonts/fa-regular-400.ttf
    _static/vendor/fontawesome/webfonts/fa-regular-400.woff2
    _static/vendor/fontawesome/webfonts/fa-solid-900.ttf
    _static/vendor/fontawesome/webfonts/fa-solid-900.woff2
    _static/webpack-macros.html
    characteristic.html
    community.html
    contribution.html
    contribution/documentation.html
    contribution/report.html
    developer.html
    developer/coding_style.html
    developer/debug.html
    developer/release.html
    faq.html
    faq/mmap_cannot_allocate_memory.html
    genindex.html
    index.html
    install.html
    install/almalinux.html
    install/centos.html
    install/debian.html
    install/docker.html
    install/fedora.html
    install/macos.html
    install/oracle-linux.html
    install/others.html
    install/ubuntu.html
    install/windows.html
    news.html
    news/0.html
    news/1.html
    news/10.html
    news/11.html
    news/12.html
    news/13.html
    news/14.html
    news/2.html
    news/3.html
    news/4.html
    news/5.html
    news/6.html
    news/7.html
    news/8.html
    news/9.html
    objects.inv
    reference.html
    reference/full_text_search.html
    reference/full_text_search/boolean_mode.html
    reference/full_text_search/scoring.html
    reference/limitations.html
    reference/optimizations.html
    reference/server_variables.html
    reference/sql_commands.html
    reference/status_variables.html
    reference/udf.html
    reference/udf/mroonga_command.html
    reference/udf/mroonga_escape.html
    reference/udf/mroonga_highlight_html.html
    reference/udf/mroonga_last_insert_grn_id.html
    reference/udf/mroonga_normalize.html
    reference/udf/mroonga_snippet.html
    reference/udf/mroonga_snippet_html.html
    search.html
    searchindex.js
    tutorial.html
    tutorial/installation_check.html
    tutorial/mode.html
    tutorial/storage.html
    tutorial/wrapper.html
    upgrade.html)
