#! /bin/sh

set -e

prevver="$2"

install_plugin() {
    cat <<EOS | mysql --defaults-file=/etc/mysql/debian.cnf
INSTALL PLUGIN groonga SONAME 'ha_groonga.so';
CREATE FUNCTION last_insert_grn_id RETURNS INTEGER soname 'ha_groonga.so';
EOS
}

case "$1" in
    configure)
        install_plugin
        ;;
    abort-upgrade|abort-deconfigure|abort-remove)
        :
        ;;
    *)
        echo "Called with unknown argument $1, bailing out."
        exit 1
        ;;
esac

#DEBHELPER#
