name: Publish to Launchpad
on:
  push:
    paths:
      - ".github/workflows/publish-launchpad.yml"
      - "doc/source/news/*"
  pull_request:
    paths:
      - ".github/workflows/publish-launchpad.yml"
      - "doc/source/news/*"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Download artifacts
        if: |
          github.ref_type == 'tag'
        timeout-minutes: 90
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          workflows=(linux.yml windows.yml)
          for workflow in "${workflows[@]}"; do
            run_id=""
            while true; do
              echo "Waiting for run to start ${workflow}..."
              run_id=$(gh run list \
                         --branch ${GITHUB_REF_NAME} \
                         --jq '.[].databaseId' \
                         --json databaseId \
                         --limit 1 \
                         --workflow ${workflow})
              if [ -n "${run_id}" ]; then
                break
              fi
              sleep 300
            done
            gh run watch \
              --exit-status \
              --interval 300 \
              ${run_id}
            gh run download ${run_id} \
              --dir release-artifacts \
              --pattern "release-source"
          done
      - name: Prepare for Launchpad publishing
        if: |
          github.ref_type == 'tag'
        run: |
          cp release-artifacts/release-source/mroonga-*.tar.gz ./
          sudo apt update
          sudo apt install -y \
            build-essential \
            debhelper \
            devscripts
      - uses: actions/checkout@v7
        with:
          path: groonga
          repository: groonga/groonga
      - uses: actions/checkout@v7
        with:
          path: apache-arrow
          repository: apache/arrow
      - name: Publish to Launchpad
        if: |
          github.ref_type == 'tag'
        env:
          APACHE_ARROW_REPOSITORY: ${{ github.workspace }}/apache-arrow
          GROONGA_REPOSITORY: ${{ github.workspace }}/groonga
          LAUNCHPAD_DEPLOY_KEY: ${{ secrets.LAUNCHPAD_DEPLOY_KEY }}
          LAUNCHPAD_UPLOADER_PGP_KEY: "0x32862FBCD63D72C152EFF3A9BD481CAA9168EA87"
        run: |
          echo "${LAUNCHPAD_DEPLOY_KEY}" | gpg --import
          echo "trusted-key ${LAUNCHPAD_UPLOADER_PGP_KEY}" > ~/.gnupg/gpg.conf
          rake -C packages ubuntu
